<?php

use Drupal\Core\Form\FormStateInterface;


/*
function comuni_module_theme_suggestions_fieldset_alter(array &$suggestions, array $variables, $hook){
     if (isset($variables['element']['#webform'])) {
         $webformID = str_replace("-", "_", $variables['element']['#webform']);
         $suggestions[] = $hook . '__' . $webformID;
     }
 }

function comuni_module_theme_suggestions_form_element_alter(array &$suggestions, array $variables, $hook){
     if (isset($variables['element']['#webform'])) {
         $webformID = str_replace("-", "_", $variables['element']['#webform']);
         $suggestions[] = $hook . '__' . $webformID;
          if (!empty($variables['element']['#type'])) {
            $suggestions[] = $hook . '__' . $webformID . '__' . $variables['element']['#type'];
          }
     }
 }*/

function comuni_module_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Adding custom validation for the welcome page type field.
  if ($form_id == 'node_appuntamento_edit_form' || $form_id == 'node_ticket_edit_form' || $form_id == 'node_valutazione_edit_form'){
    $form['#disabled'] = array('#type' => 'hidden',
      '#title' => t('Row 3. Column 1'),
      '#required' => FALSE,
      '#default_value' => 0,
      '#disabled' => TRUE,
    );
  }
}

function comuni_module_preprocess_page(&$variables) {
    $variables['bit_svg'] = './modules/custom/design-comuni-drupal-theme/comuni_theme/node_modules/bootstrap-italia/dist/svg/sprites.svg';
    if(file_exists($variables['bit_svg'])){
      $variables['bit_svg'] = file_get_contents($variables['bit_svg']);
    }
    $variables['logo_svg'] = './modules/custom/design-comuni-drupal-theme/comuni_theme/assets/img/logo-comune.svg';
    if(file_exists($variables['logo_svg'])){
      $variables['logo_svg'] = file_get_contents($variables['logo_svg']);
    }
}